name: Upload Gradle Package

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  GCP_PROJECT_ID: heekkr

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: gcp
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: java

    steps:
      - uses: actions/checkout@v3

      - id: configure-version
        name: Configure Version
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          VERSION=${TAG_NAME#"v"}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Google auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
          build-root-directory: java/

      - name: Publish
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: |
            publish
            -Pversion=${{ steps.configure-version.outputs.version }}
          build-root-directory: java/
