name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  GCP_PROJECT_ID: heekkr

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: gcp
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: python

    steps:
      - uses: actions/checkout@v3

      - name: Configure Environment Variables
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          VERSION=${TAG_NAME#"v"}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Google auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Configure Version
        run: |
          sed -i -e 's/^version = \"0.0.0\"$/version = "'"$VERSION"'"/' pyproject.toml

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: "1.5.1"

      - name: Install dependencies
        run: poetry install

      - name: Build package
        run: poetry build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: python/dist

      - name: Configure Private Registry
        run: |
          poetry config repositories.gar https://asia-northeast3-python.pkg.dev/heekkr/heekkr-python/
          poetry self add keyrings.google-artifactregistry-auth

      - name: Publish package
        run: poetry publish -r gar
