name: Upload Web Package

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  GCP_PROJECT_ID: heekkr

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: gcp
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v3

      - name: Configure Environment Variables
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          VERSION=${TAG_NAME#"v"}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Google auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Configure Google Artifact Registry Authentication
        run: |
          yarn config set -H npmAuthToken $(gcloud auth print-access-token)

      - run: yarn install --immutable

      - run: yarn generate

      - name: Configure Version
        run: |
          sed -i -e 's/"version": "0.0.0"/"version": "'"$VERSION"'"/' package.json

      - run: yarn npm publish
